name: docsynk-landing
region: nyc
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: sileroka/docsynk-landing
    build_command: npm run build:prod
    run_command: npx serve dist/docsynk-landing-temp/browser -s -l 8080
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    health_check:
      http_path: /
